"""empty message

Revision ID: 43c932653760
Revises: b6507f47d8de
Create Date: 2021-01-24 19:07:15.027956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c932653760'
down_revision = 'b6507f47d8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Location', sa.Column('link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Location', 'link')
    # ### end Alembic commands ###
