"""empty message

Revision ID: c19d9ee21fb6
Revises: 43c932653760
Create Date: 2021-01-26 16:48:41.947329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19d9ee21fb6'
down_revision = '43c932653760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TimeSlots', sa.Column('free', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TimeSlots', 'free')
    # ### end Alembic commands ###
